name: ci
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      container: ${{ steps.filter.outputs.container }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # @v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0

        # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c
        id: filter
        with:
          filters: |
            container:
              - '.github/**'
              - 'Dockerfile'
              - 'spack.yaml'

  container:
    if: ${{ needs.changes.outputs.container == 'true' }}
    needs: changes
    uses: ./.github/workflows/container.yml

  all:
    needs:
     - changes
     - container
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Status summary
      run: |
        if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
          echo "One or more required jobs failed or were cancelled"
          exit 1
        else
          echo "All jobs completed successfully"
        fi
