name: Build & Push Container
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/develop' }}
          tags: ghcr.io/spack/spack-distroless:latest
          cache-from: type=registry,ref=ghcr.io/spack/spack-distroless:buildcache
          cache-to: ${{ github.ref == 'refs/heads/develop' && 'type=registry,ref=ghcr.io/spack/spack-distroless:buildcache,mode=max' || '' }}
