name: Build & Push Container
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/develop' }}
          tags: ghcr.io/spack/spack-distroless:latest
          cache-from: type=registry,ref=ghcr.io/spack/spack-distroless:buildcache
          cache-to: ${{ github.ref == 'refs/heads/develop' && 'type=registry,ref=ghcr.io/spack/spack-distroless:buildcache,mode=max' || '' }}
