name: Build & Push Container
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@32945a339266b759abcbdc89316275140b0fc960
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/develop' }}
          tags: ghcr.io/spack/spack-distroless:latest
          cache-from: type=registry,ref=ghcr.io/spack/spack-distroless:buildcache
          cache-to: ${{ github.ref == 'refs/heads/develop' && 'type=registry,ref=ghcr.io/spack/spack-distroless:buildcache,mode=max' || '' }}
