name: dependabot

on:
  push:
    branches:
      - 'dependabot/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.repository == 'spack/spack-distroless'}}
    steps:
      - name: Get PR associated with Branch
        id: branch
        run: echo "url=$(gh pr list --head ${GITHUB_REF##*/} --json url --template '{{range .}}{{.url}}{{end}}')\n" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REF: ${{ github.ref_name }}

      - name: Auto Approve Dependabot PRs
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ steps.branch.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ steps.branch.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
